### ISSUE TITLE
Physician performance estimate variance?

### ISSUE THREAD

**Issue by MHamza-Y** [FlemmingKondrup/DeepVent#2]
Hi,

I saw that in the table 1 of the paper, the physicians have a std of 0.007. However, the [code](https://github.com/FlemmingKondrup/DeepVent/blob/c7d06abc5dbde4e991713d377db73e9200e9be80/evaluation/estimator.py#L89C16-L89C16) used to estimate the physician performance is deterministic. Why and how the variance was calculated?

**Comment by FlemmingKondrup** [comment]
You are correct, the performance evaluation of the physician performance estimator gives a single value. However, to ensure reliability of our results, we ran each method 5 times, and averaged the result.
